# Generated by Django 5.1.7 on 2025-03-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='cliente',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='data_hora',
            new_name='date_hour',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='dono',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='criado_em',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dono',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone',
            new_name='phone',
        ),
    ]
