# Generated by Django 5.1.7 on 2025-03-16 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_cliente_agendamento_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendamento',
            new_name='Appointment',
        ),
    ]
