# Generated by Django 5.1.7 on 2025-03-16 20:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_agendamento_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Client',
        ),
    ]
